### PR TITLE
Validate desktop file after build

### PR DESCRIPTION
**Pull request by mattahorton**
We talked in discussion on #705 about making this something we put into our build steps. Here that is.

### CODE REVIEW

**Comment by cchafe** [comment]
I checked out the branch and my usual qmake build fails.
git checkout gha/validate-desktop-file
qmake
make clean
make release
(I wonder why it passed the tests and what I'm doing wrong)

src/gui/virtualstudio.cpp: In member function ‘void VirtualStudio::toVirtualStudio()’:
src/gui/virtualstudio.cpp:538:54: error: cannot convert ‘VirtualStudio::toVirtualStudio()::<lambda(QAbstractOAuth::Stage, QVariantMap*)>’ to ‘const QAbstractOAuth::ModifyParametersFunction&’ {aka ‘const std::function<void(QAbstractOAuth::Stage, QMultiMap<QString, QVariant>*)>&’}
  538 |         m_authenticator->setModifyParametersFunction([](QAbstractOAuth2::Stage stage,
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      |
      |                                                      VirtualStudio::toVirtualStudio()::<lambda(QAbstractOAuth::Stage, QVariantMap*)>
  539 |                                                         QVariantMap* parameters) {
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
  540 |             if (stage == QAbstractOAuth2::Stage::RequestingAccessToken) {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  541 |                 QByteArray code = parameters->value(QStringLiteral("code")).toByteArray();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  542 |                 (*parameters)[QStringLiteral("code")] = QUrl::fromPercentEncoding(code);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  543 |             } else if (stage == QAbstractOAuth2::Stage::RequestingAuthorization) {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  544 |                 parameters->insert(QStringLiteral("audience"),
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  545 |                                    QStringLiteral("https://api.jacktrip.org"));
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  546 |             }
      |             ~                                         
  547 |             if (!parameters->contains("client_id")) {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
  548 |                 parameters->insert("client_id", "cROUJag0UVKDaJ6jRAKRzlVjKVFNU39I");
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  549 |             }
      |             ~                                         
  550 |         });
      |         ~

**Comment by mattahorton** [comment]
Have you tried to build dev or main in a bit? This PR doesn't affect the code at all. It's really just for the github actions scripts.

**Comment by mattahorton** [comment]
Fwiw @cchafe, I ran that exact series of commands and it built fine on macOS with Qt 5.15.5_1. 

What version of Qt are you running?

**Comment by cchafe** [comment]
good hint -- thanks 
I was on qt6, so switched to 5.15.5 and it's fine

**Comment by cchafe** [comment]
after a fresh pull
sudo make install does the right thing
but if I do a make clean beforehand then install fails because clean removes the .desktop file

**Review by nwang92 — APPROVED** [review]

**Comment by dyfer** [comment]
> but if I do a make clean before compiling then install fails because clean removes the .desktop file

It seems this should be addressed before merging this PR, right?

**Comment by mattahorton** [comment]
I still do not understand why anything about a local build would be affected by a Github Actions change. I only edited the yml file here, nothing about the desktop file. This should not affect local builds at all.

**Comment by cchafe** [comment]
It's a separate issue and happens with the current dev branch.

**Comment by dyfer** [comment]
> I still do not understand why anything about a local build would be affected by a Github Actions change. I only edited the yml file here, nothing about the desktop file. This should not affect local builds at all.

Yes, sorry for the noise. I commented before looking at what this PR changed. I just thought that it might be a simple fix in https://github.com/jacktrip/jacktrip/blob/dev/jacktrip.pro#L190, but I agree this is out of scope of this PR. Also, I don't have access to a Linux machine to try fixing that.

**Pull request merged**
