### PR TITLE
Release 1.5.3

### PR DESCRIPTION
**Pull request by ntonnaett**
Don't merge, Just approve!

### CODE REVIEW

**Review by cchafe — APPROVED** [review]

**Comment by OConnorStP** [comment]
could we hold off on release at least until the call this Thursday?  i'd like to talk over a few ideas about how to expose the release process to a broader group of people.  we had a useful discussion about this several calls ago, but it seems to me there's some work left to go.  these tiny-releases are hard to sell right now, especially the way they're described.

**Comment by ntonnaett** [comment]
The release already happened.

**Comment by dyfer** [comment]
Sorry, haven't noticed, my bad.

**Comment by ntonnaett** [comment]
The change we need for #496 is actually a breaking change. So we even have to discuss what version we call this then.

**Comment by OConnorStP** [comment]
I saw it go by, but was hoping against hope that I'd misunderstood and that it was still in queue.  ;-)

**Pull request merged**
