### PR TITLE
bump dev to 1.5.3 and bugfix for plc

### PR DESCRIPTION
**Pull request by cchafe**
in JackTrip.cpp where channel count for Regulator was meant to be mNumAudioChansOut not mNumAudioChansIn

### CODE REVIEW

**Comment by cchafe** [comment]
something's up with clang-format
before committing I did
clang-format -i src/jacktrip_globals.cpp src/jacktrip_globals.h
clang-format -i src/JackTrip.cpp src/JackTrip.h
but it's failing -- let me know what's incorrect if you can

**Comment by ntonnaett** [comment]
It looks like you are using an older clang-format version. I think we are on version 13. Are you on Fedora 35?

**Comment by cchafe** [comment]
clang-format version 13.0.0 (Fedora 13.0.0-3.fc35)

**Comment by ntonnaett** [comment]
I have the same version. When I run `clang-format -i src/jacktrip_globals.* src/JackTrip.*` it reverses the indentation changes from this PR.

**Comment by ntonnaett** [comment]
We should merge this to dev first. I'll change the base.

**Comment by cchafe** [comment]
that was it... too many machines in my life (meaning more than one)
sorry about the confusion

**Comment by cchafe** [comment]
right -- should be dev not main

**Comment by ntonnaett** [comment]
Maybe we should talk in the next dev meeting about letting the github action add a formatting commit when necessary.

**Review by ntonnaett — APPROVED** [review]

**Comment by cchafe** [comment]
if you mean auto-format on commit, I'm all for it

**Pull request merged**
