### PR TITLE
Update .mailmap

### PR DESCRIPTION
**Pull request by omarcostahamido**
- fix email address, please.

### CODE REVIEW

**Comment by omarcostahamido** [comment]
@mikedickey 
@mattahorton 
@nwang92 
if you could aprove and merge, I would greatly appreciate it!

**Comment by omarcostahamido** [comment]
@cchafe 
@dhing1024 
anyone can help with this?

**Review by mikedickey — APPROVED** [review]

**Comment by omarcostahamido** [comment]
@mikedickey 
THank you for getting back to me.
Currently switching to patch-3 branch causes an error:
`fatal: not a git repository: externals/doxygen-awesome-css/../../.git/modules/documentation/doxygen-awesome-css`
better if I just recreate this PR on from dev, cause I can't access my own branch.

**Comment by omarcostahamido** [comment]
DONE, if #1061 works, then you can close this one?

**Pull request closed without merging**
