### PR TITLE
Set keychain path for notarization

### PR DESCRIPTION
**Pull request by mattahorton**
This [fixes notarization](https://github.com/jacktriplabs/jacktrip/actions/runs/3363802016). It borrows the same app signing keychain created for use in the github actions script.

We'll need to get this to dev and then main and then redo the release creation.

### CODE REVIEW

**Comment by ntonnaett** [comment]
@dvzrv pointed out that the checksums for version 1.6.5 is locked downstream. So we might want to skip this version and release 1.6.6.

**Comment by mattahorton** [comment]
That shouldn't block this PR

**Review by nwang92 — APPROVED** [review]

**Comment by psiborg112** [comment]
Could you please test #786? This will break my workflow.

**Comment by psiborg112** [comment]
And it relies on the assumption that apple will never change the way its security tool generates keychain names and locations.

**Comment by dvzrv** [comment]
> So we might want to skip this version and release 1.6.6.

As mentioned in https://github.com/jacktrip/jacktrip/issues/785#issuecomment-1297701613 this might not be necessary, as the only downstream (that I am aware of currently) still/ already packaging 1.6.5 is Manjaro which will eventually get the package that I am building anyways, as they don't build their own packages (mostly).

For the future it might be worth looking into using semver's [build metadata](https://semver.org/#spec-item-10) for situations in which not all build artifacts behave the way you expect them to on a release (see https://github.com/jacktrip/jacktrip/issues/785#issuecomment-1297261428).

**Comment by mattahorton** [comment]
> For the future it might be worth looking into using semver's [build metadata](https://semver.org/#spec-item-10) for situations in which not all build artifacts behave the way you expect them to on a release (see [#785 (comment)](https://github.com/jacktrip/jacktrip/issues/785#issuecomment-1297261428)).

Honestly, another part of the solution is to not fail signing all signed artifacts when one platform fails. The reason I felt it necessary to delete the release at the time (agreed in retrospect it was a bad decision), was that we now had unsigned Windows builds sitting in the release where many people have been pointed to for downloads for years.

If we were able to provide the appropriate builds, maybe just delete the macOS ones and then add them back once they've been signed and notarized, that would be better. But our current scripts rely on both platforms succeeding to upload any artifacts at all.

**Comment by mattahorton** [comment]
Closing in favor of #788

**Pull request closed without merging**
