### PR TITLE
VS: Deeplink Fixes

### PR DESCRIPTION
**Pull request by mattahorton**
Fixes deep links not working. Especially when user has the app open and is on the browse page.

### CODE REVIEW

**Comment by nwang92** [comment]
When switching from "Prod" to "Test" mode, my applet gets stuck here and the "Back" button does not do anything clicked
Screenshot 2022-11-21 at 9 11 22 AM

**Comment by nwang92** [comment]
I caught a case where clicking the "Leave" button showed me the "Disconnected" text, but it didn't actually go back to the "Browse" screen

https://user-images.githubusercontent.com/6201822/203125059-c0e34b2a-2226-4721-9cfd-7f2926b14761.mov

**Comment by mattahorton** [comment]
@nwang92 try now?

**Comment by nwang92** [comment]
Both issues I found above are fixed now

**Review by nwang92 — APPROVED** [review]

**Comment by nwang92** [comment]
Approved although I don't know if I understand the nuances of the code super well. But I'm going to keep using this build and I'll let you know if I encounter any new errors.

**Review by mikedickey — APPROVED** [review]

**Comment by mikedickey** [comment]
+1 to what @nwang92 said ;)

**Pull request merged**
