### PR TITLE
[Linux] Add symbolic icon

### LINKED ISSUE #365: Symbolic monochrome icon missing
Gnome Shell shows a symbolic link of applications in the topbar. Right now JackTrip's icon gets converted to greyscale and this doesn't look right. We should add a black and white version of the logo. SVG should be sufficient.

### PR DESCRIPTION
**Pull request by ntonnaett**
This fixes #365 thanks to @codedoser. The symbolic icon is most prominently shown in the top bar of Gnome Shell when the JackTrip window is focused. But there might be other occurrences I'm not aware of.

### CODE REVIEW

**Comment by dyfer** [comment]
This looks fine, but it made no change to the icon appearance on my system (Ubuntu 20.04, Gnome 3.36.8). Actually, even if I remove all the icons (48px, scalable, and this one symbolic), there's still a little icon on the top bar when JT is in focus (despite showing no app icon otherwise). Looks like it's cached somewhere - might be something about my system...

Have you tested this and does it appear correctly for you? Which version of Gnome have you tested with?

**Comment by ntonnaett** [comment]
What icon do you see? The old one?

**Comment by ntonnaett** [comment]
Did you logout and login again after installing the icon? I forgot (to mention) that gnome seems to create the icon cache at startup.

**Comment by dyfer** [comment]
> Did you logout and login again after installing the icon? 

Yes, I even restarted.

> What icon do you see? The old one?

Yes, I see the old icon, but again it's weird, because I can see it even after 1) removing all icons manually and 2) restarting the system. Not sure where it's cached.

**Comment by ntonnaett** [comment]
What prefix did you use? What Qt version are you using? I remember that there was a change to use those icon files instead of a qt resource. But I'm not sure how a qt resource icon could work on Linux. But this would be only one type of icon I think.

**Comment by dyfer** [comment]
> What prefix did you use? 

`/usr/local`, seems that was the default

> What Qt version are you using? 

5.12.8

> I remember that there was a change to use those icon files instead of a qt resource. But I'm not sure how a qt resource icon could work on Linux. But this would be only one type of icon I think.

Not sure I understand. Is there a qt resource icon that might be in use instead? Where's that located?

**Comment by ntonnaett** [comment]
Could you try using just `/usr` as prefix? Usually you wouldn't want this because it can conflict with your distribution's installation of jacktrip.

qt resources are precompiled resources into C++ or C source code. It has pros and cons. One con is that it is compiled into the binary. What is also a pro...

**Comment by dyfer** [comment]
I'll try `/usr` and report back.
I skimmed through our source and I can see no qt resource icons, aside from one for windows that seems to be used only in cmake build, AFAICT.

**Comment by ntonnaett** [comment]
https://github.com/jacktrip/jacktrip/blob/dev/src/gui/qjacktrip.qrc

**Comment by dyfer** [comment]
> https://github.com/jacktrip/jacktrip/blob/dev/src/gui/qjacktrip.qrc

Ah, I missed that. Thanks, good to know.

**Comment by dyfer** [comment]
In that case, wouldn't it be better to modify `icon.png` to be thicker (though still in color)? I'm not sure it would be, but maybe something to consider...?

**Comment by ntonnaett** [comment]
This is the main icon on other platforms.

**Comment by dyfer** [comment]
> This is the main icon on other platforms.

I think it's only used on Windows and my thought was that since it's small anyway it wouldn't be bad if it's thicker. It's just a suggestion, if you don't think that's a good approach that's fine.

As for this PR, it looks fine, but I really can't tell if it's doing anything on my system.

**Comment by dyfer** [comment]
After installing in `/usr`, here's my result:
- symbolic icon shows up as the JT icon in the application launcher (instead of the "red" icon)
- the icon in the taskbar is the correct "red" icon
- the icon on the top bar is still the previous one (thin)

I think the first point is suboptimal, I'd expect to see the main JT icon when searching for it in the launcher. 

Are you seeing the correct behavior on your system with this change?

**Comment by ntonnaett** [comment]
You can uninstall the last install with `ninja uninstall`.

Could you try again? I removed the symbolic from the filename.

**Comment by dyfer** [comment]
I still would like to get the answer whether this works/worked on your system.

**Comment by ntonnaett** [comment]
If it wouldn't work on my system I would try to fix that first. But Ubuntu should also work. At least the wrong launcher icon is fixed now.

**Comment by dyfer** [comment]
Just so it's clear: with the latest update to this PR, _I see no change in behavior in relation to what this PR originally provided_. I get the symbolic icon in the launcher (undesirable), and "thin" icon in the top bar (no change from the regular `dev` build).

**Comment by dyfer** [comment]
@ntonnaett I was trying to move around that symbolic icon between `/usr/` and `/usr/local` prefixes, installing JT in either, naming the icon with and without "-symbolic" and I can't reproduce having the symbolic icon show up in my application launcher anymore. (It still never showed up at the top bar, where it should've). Maybe there's something weird going on with my system. Someone else on Ubuntu should probably try this (maybe at some point I'll set up a VM with a clean install...). Sorry I can't be of more help.

**Comment by ntonnaett** [comment]
Thanks for your help. I appreciate that. Last night I had an epiphany. Ubuntu uses X11 instead of Wayland. The symbolic icon that is chosen from the WM_CLASS name that is set by the application. That defaults to lowercase application id on wayland but the binary name on X11. What's missing here is that JackTrip sets the WM_CLASS. That should be possible by setting the desktop file's basename with QGuiApplication::setDesktopFileName(). But right now JackTrip is only a QCoreApplication. @psiborg112 Could you help? Is it possible to switch to QGuiApplication for the gui runtime? Or did you try that already?

**Comment by dyfer** [comment]
I support fixing/adding this, but since it's a rather cosmetic issue and it might involve more work to get right, maybe we don't need this to happen in 1.4.0? IMO the users would benefit if we release 1.4.0 sooner with all its improvements already in. 

Other than this it seems we are ready for either another RC (due to the recent PR for closing jack ports) or possibly for the final release, what do you think?

**Comment by ntonnaett** [comment]
Yes. I tried a lot today to fix this. No clue what's wrong with X11. Let's release 1.4.0. There's only #358 left after this.

**Comment by ntonnaett** [comment]
I think we can merge this. So it works on wayland and fix X11 after the release.

**Comment by dyfer** [comment]
All right. Should I add the icon copy to qmake or would you do that? We'd need to add something like this towards the end of `jacktrip.pro` (untested):

````
icon_symbolic.extra = cp $${PWD}/linux/icons/jacktrip-symbolic.svg $${OUT_PWD}/$${application_id}-symbolic.svg
icon_symbolic.CONFIG += no_check_exist
icon_symbolic.files = $${OUT_PWD}/$${application_id}-symbolic.svg
icon_symbolic.path = $${PREFIX}/share/icons/hicolor/symbolic/apps

INSTALLS += (...) icon_symbolic
```

**Comment by ntonnaett** [comment]
Installation with QMake works as expected.

**Review by dyfer — APPROVED** [review]
Thanks! Sorry for the delay.

**Pull request merged**
