### PR TITLE
Meson build support

### PR DESCRIPTION
**Pull request by ntonnaett**
This adds meson as alternative to building jacktrip with qmake. It's tested with Fedora Linux. Other Linux distributions should just work. I would be very interested in the experience under Windows and MacOS.
Meson should be installed by default with recent Linux distributions. For Windows and Mac you can look [here](https://mesonbuild.com/Getting-meson.html).

Following commands build jacktrip (debug and unoptimized by default):
cd jacktrip
meson builddir
ninja -C builddir

To install in default location (e.g. /usr/local/bin):
ninja -C builddir install

### CODE REVIEW

**Comment by michaeldessen** [comment]
Thanks for working on this. I installed meson via macports then tried this on macos 10.14 and got errors. Not sure if it's some problem on my end but in case it helps the full log is below.
Michael

---

Build started at 2020-06-08T17:42:19.019370
Main binary: /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
Build Options: 
Python system: Darwin
The Meson build system
Version: 0.53.2
Source dir: /Users/mdessen/Documents/GitHub/jacktrip
Build dir: /Users/mdessen/Documents/GitHub/jacktrip/builddir
Build type: native build
Project name: jacktrip
Project version: 1.2
No CXXFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /Users/mdessen/Documents/GitHub/jacktrip/builddir/meson-private/sanitycheckcpp.cc -o /Users/mdessen/Documents/GitHub/jacktrip/builddir/meson-private/sanitycheckcpp.exe -pipe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /Users/mdessen/Documents/GitHub/jacktrip/builddir/meson-private/sanitycheckcpp.exe
C++ compiler for the build machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C++ linker for the build machine: c++ ld64 450.3
No CXXFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /Users/mdessen/Documents/GitHub/jacktrip/builddir/meson-private/sanitycheckcpp.cc -o /Users/mdessen/Documents/GitHub/jacktrip/builddir/meson-private/sanitycheckcpp.exe -pipe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /Users/mdessen/Documents/GitHub/jacktrip/builddir/meson-private/sanitycheckcpp.exe
C++ compiler for the host machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
C++ linker for the host machine: c++ ld64 450.3
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
WARNING: rcc dependencies will not work reliably until this upstream issue is fixed: https://bugreports.qt.io/browse/QTBUG-45460
Trying to find qt with pkg-config
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.HOST at ['/opt/local/bin/pkg-config']
Found pkg-config: /opt/local/bin/pkg-config (0.29.2)
Determining dependency 'Qt5Core' with pkg-config executable '/opt/local/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config --modversion Qt5Core` -> 0
5.14.1
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config --cflags Qt5Core` -> 0
-DQT_CORE_LIB -F/opt/local/libexec/qt5/lib -I/opt/local/libexec/qt5/lib/QtCore.framework/Headers -I/opt/local/libexec/qt5/include
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config Qt5Core --libs` -> 0
-F/opt/local/libexec/qt5/lib -framework QtCore
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config Qt5Core --libs` -> 0
-F/opt/local/libexec/qt5/lib -framework QtCore
Pkg-config binary for MachineChoice.HOST is cached.
Determining dependency 'Qt5Network' with pkg-config executable '/opt/local/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config --modversion Qt5Network` -> 0
5.14.1
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config --cflags Qt5Network` -> 0
-DQT_NETWORK_LIB -F/opt/local/libexec/qt5/lib -DQT_CORE_LIB -F/opt/local/libexec/qt5/lib -I/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers -I/opt/local/libexec/qt5/include -I/opt/local/libexec/qt5/lib/QtCore.framework/Headers -I/opt/local/libexec/qt5/include
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config Qt5Network --libs` -> 0
-F/opt/local/libexec/qt5/lib -framework QtNetwork -F/opt/local/libexec/qt5/lib -framework QtCore
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config Qt5Network --libs` -> 0
-F/opt/local/libexec/qt5/lib -framework QtNetwork -F/opt/local/libexec/qt5/lib -framework QtCore
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config --variable=host_bins Qt5Core` -> 0
/opt/local/libexec/qt5/bin
Got pkgconfig variable host_bins : /opt/local/libexec/qt5/bin
Run-time dependency qt5 (modules: Core, Network) found: YES 5.14.1 (pkg-config)
Pkg-config binary for MachineChoice.HOST is cached.
Determining dependency 'jack' with pkg-config executable '/opt/local/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/opt/local/bin/pkg-config --modversion jack` -> 1

Finding framework path by running:  c++ -v -E - -pipe 

Looking for framework jack in /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks
CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Trying CMake binary cmake for machine MachineChoice.HOST at [None]
Did not find CMake 'cmake'
Found CMake: NO
No CMake binary for machine MachineChoice.HOST not found. Giving up.
Run-time dependency jack found: NO (tried pkgconfig and framework)

meson.build:4:0: ERROR: Dependency "jack" not found, tried pkgconfig and framework

---

**Comment by ntonnaett** [comment]
The jack library is missing. I'm not quiet sure yet how to handle this. There is Homebrew and Macports on MacOS. Homebrew has only jack1, Macports jack2. But Macports seems technically more complicated.
There's a third option: meson wrapdb. If meson doesn't find a required dependency on the system it can just get it upstream. But then the external library has to get a meson.build and a wrapdb file.
I will look into it. 

In the meantime. Maybe you saw the INSTALL_meson.md. There I included instructions for MacOS with brew (that I didn't test). Maybe you could try that.

**Comment by michaeldessen** [comment]
Unfortunately I don't have brew, only macports, and I don't want to install a 2nd package manager since I've read that having 2 can cause conflicts. Sorry I can't help with that but I hope this can be solved since it would be great to have a simple build method on macs.

Michael

**Comment by ntonnaett** [comment]
It should also work if you install jack and rtaudio with macports. Did you install qt5 with macports? Because that works already.

**Comment by daveccrma** [comment]
I'd recommend homebrew over macports.  However, I'd probably recommend not looking into Meson just yet for Mac. I'm going to investigate making jacktrip available via homebrew itself for users that prefer that but there are some issues holding that up.

**Comment by michaeldessen** [comment]
Thank you. Having a homebrew install for jacktrip would be great.

**Comment by ntonnaett** [comment]
That's good news. Maybe I didn't mention but meson can live parallel to the existing build system without interfering. I wouldn't suggest switching to meson for the end user yet.

**Comment by cchafe** [comment]
Works fine (after install meson in Fedora 32)

**Pull request merged**
