### PR TITLE
Add manpage

### PR DESCRIPTION
**Pull request by ntonnaett**
Meson generates a manpage with help2man which parses --help and --version of jacktrip. The modifications to --help are for the output of the manpage.

```
meson builddir
cd builddir
meson compile
man -l jacktrip.1
```

### CODE REVIEW

**Comment by ntonnaett** [comment]
Solves #69

**Comment by dyfer** [comment]
This is great, thanks for the addition. 
Just in terms of workflow, how will the packagers know to generate the man page using meson? Does this need to be documented/set somewhere?

**Comment by ntonnaett** [comment]
If help2man is present on your system, meson automatically generates the manpage and installs it to the right location. I think packagers know help2man and meson tells them if it's missing. But I think the whole build documentation could be improved. For example, I just forgot about installing jacktrip with `sudo meson install`.

It might be good to talk about what the default build system should be. I just tested the qmake build and it fails on my side because it can't link to the pipewire's jack.

**Comment by ntonnaett** [comment]
I should add help2man to the dependency list.

**Comment by dyfer** [comment]
> If help2man is present on your system, meson automatically generates the manpage and installs it to the right location. I think packagers know help2man and meson tells them if it's missing. But I think the whole build documentation could be improved. For example, I just forgot about installing jacktrip with `sudo meson install`.

So should the manpage be generated now in the CI? I looked at the meson linux artifacts and couldn't see it (though I'm not sure if I'm looking for the right thing)

> I just tested the qmake build and it fails on my side because it can't link to the pipewire's jack.

How does one suppose to link with piperiwire? What's the same, what's different than linking with jack?

> It might be good to talk about what the default build system should be.

I agree, I'd prefer to maintain one build scenario. But it seems like there was no desire to make a switch from qmake last time we talked about this.

**Comment by ntonnaett** [comment]
> So should the manpage be generated now in the CI? I looked at the meson linux artifacts and couldn't see it (though I'm not sure if I'm looking for the right thing)
> 
Good point. I will add this.

> How does one suppose to link with piperiwire? What's the same, what's different than linking with jack?
It's actually the same. So I guess qmake just doesn't find it. CMake works fine.

> > It might be good to talk about what the default build system should be.
> 
> I agree, I'd prefer to maintain one build scenario. But it seems like there was no desire to make a switch from qmake last time we talked about this.

Yes, I think that needs good instructions that show the benefits too. I try to install Windows again to test that side too. The virtual machine is just annoying.

**Comment by ntonnaett** [comment]
Just to elaborate a bit. Pipewire installs their jack stuff at another place than JACK. That's good if you accidentally install both.
```
$ pkgconf --libs jack
-L/usr/lib64/pipewire-0.3/jack -ljack -ljacknet
```
Pkgconfig gives you linker flags where -L gives you the place to search. Maybe qmake doesn't use pkgconfig?

**Comment by dyfer** [comment]
> > How does one suppose to link with piperiwire? What's the same, what's different than linking with jack?
> 
> It's actually the same. So I guess qmake just doesn't find it. CMake works fine.

hm, looks like `jacktrip.pro` just hardcodes `-ljack` instead of using pkg-config. We should probably change that (for Linux and macOS)

**Review by dyfer — APPROVED** [review]
Thanks!

**Pull request merged**
