### PR TITLE
Use realtime priority for regulator worker thread

### PR DESCRIPTION
**Pull request by mikedickey**
also adding statistics on worker thread underrun when -I (iostats)

### CODE REVIEW

**Comment by mikedickey** [comment]
I am seeing that with default scheduling priority, PLC is falling behind with only a few clients. Bumping its priority is producing MUCH better results for me.

I still think it's probably better to run inside the jack callback (4) for clients, but for hubserver this is required.

**Comment by mikedickey** [comment]
FWIW i did also try using a single regulator thread, but it does not work very well at all. After a few clients with sustained (1%) loss, it starts to fall behind and is never able to catch back up. https://github.com/jacktrip/jacktrip/commit/bc3abd85d463da3aa9248a4824a9eb51165da503

**Review by nwang92 — APPROVED** [review]

**Comment by ntonnaett** [comment]
Maybe we want to do this more fine-grained. It looks like this uses the same priority as we use for the udp thread. How does this actually interact with the realtime udp thread option?

**Comment by mikedickey** [comment]
> Maybe we want to do this more fine-grained. It looks like this uses the same priority as we use for the udp thread. How does this actually interact with the realtime udp thread option?

Maybe, but realtime udp threads don't seem to scale well in hubserver mode anyway. At least as things currently stand, you should only use realtime udp threads with bufstrategy 4.

**Pull request merged**
