### PR TITLE
Arunov/jitter buffer

### PR DESCRIPTION
**Pull request by antonrunov**
New Jitter Buffer implementation.

Includes following features:
- New jitter buffer with 2 different buffering strategies (--bufstrategy 1 (default) and --bufstrategy 2). The old implementation can be turned back with (--buffstrategy -1).
- Support for mixed FPP (Frames per Period), requires both server and client using the new JB.
- Broadcast output (use --broadcast <broadcast_queue> to enable it).
- Automatic queue length configuration (-q auto)
- An option to set RT thread priority for UdpDataProtocol thread (--udprt).

### CODE REVIEW

**Comment by josmithiii** [comment]
All of my tests pass on a branch I created consisting of dev with arunov/jitter-buffer merged in (no merge conflicts).

**Comment by psiborg112** [comment]
I've been using the jitter buffer in qjacktrip for a while now and everything has been running fine. Only issue I found was that mBroadcast is used uninitialised in JackAudioInterface.cpp when broadcast isn't enabled. (Adding "mBroadcast(false)," at line 84 fixes this.)

**Comment by antonrunov** [comment]
Good call, thanks @psiborg112. I missed it indeed. Will push a fix shortly.

**Review by mikedickey — APPROVED** [review]

**Comment by mikedickey** [comment]
I've re-run scale tests on this branch and it's working great. Going to squash and merge so we can update and work on Aaron's branch next.

**Pull request merged**
