### PR TITLE
Too many hubs

### PR DESCRIPTION
**Pull request by psiborg112**
Was just merging some changes from the master back into my branch and noticed that we may have been a little overzealous with the renaming of hub to master. It's affected a few of the external libraries which I've reverted back here. It may also have affected the binary file libjack.dll. (So if anyone has an appropriate copy of that handy, it might not hurt to reupload it because we may have broken it.)

### CODE REVIEW

**Comment by cchafe** [comment]
The rename (using SED) replaced all occurences of "master" with "hub" -- I can't remember if I did that recursively down into /externals -- would that have been the cause?

**Comment by psiborg112** [comment]
That would have done it if it was recursive.

**Comment by cchafe** [comment]
Did it break a compile? The current version of master compiles ok.

**Comment by psiborg112** [comment]
It would only break if someone was actually building using the externals that we're supplying. (And most people probably aren't.) And it's kind of moot if we decide to do away with the externals folder entirely.

**Comment by ntonnaett** [comment]
I would support the decision to remove the externals folder. The library versions seem to be pretty outdated. AFAIK we don't encourage to use it on any platform. Please correct me if I'm wrong.

**Comment by psiborg112** [comment]
This is resolved in the dev branch with the removal of the externals folder, so I'm closing this now.

**Pull request closed without merging**
