### PR TITLE
Release 1.6.5

### PR DESCRIPTION
**Pull request by mattahorton**

### CODE REVIEW

**Comment by mattahorton** [comment]
We'll need to merge #780 before we merge this one

**Comment by ntonnaett** [comment]
Have you updated the changelog file?

**Comment by mattahorton** [comment]
> Have you updated the changelog file?

it was updated for the rc.1 and not much has changed since then

**Comment by mattahorton** [comment]
I cannot figure out why there is a conflict on this file any longer. I fixed a typo and merged in changes that were in main.

**Review by nwang92 — APPROVED** [review]

**Pull request merged**
