### PR TITLE
VU meters in standard mode

### PR DESCRIPTION
**Pull request by psiborg112**
Adds a VU meter window to the standard GUI.

### CODE REVIEW

**Comment by psiborg112** [comment]
If someone could test that this works OK with RtAudio, that would be great. I'm particularly interested in checking the scenario where more audio channels are requested than are available on the interface.

**Comment by dyfer** [comment]
I think that adding VU meters for non-vs mode is great and needed, thanks!

I'm just not sure if I'm convinced by the idea of a separate window.
While this might require more thought, I'd prefer if the meters were integrated in the main window. The main window ideally shouldn't have controls inactive while connected IMO so that one can switch between tabs. OTOH I'm not sure which tab should meters should be added to...

> If someone could test that this works OK with RtAudio, that would be great. I'm particularly interested in checking the scenario where more audio channels are requested than are available on the interface.

You probably know this but FYI - you can always download the regular build from github actions (which has the rtaudio backend). I tried requesting more channels than available on the device and it seems fine (meters show up but no signal appears).

**Comment by psiborg112** [comment]
It's more an issue that RtAudio just ends up being a layer over JACK for me on my main dev machine. I think eventually it would be good to rework the GUI: when it was first created there weren't as many options to include, so tabs made sense. Most of this should probably move to a separate settings window now. And when that happens, I'll move the meters back to the main window.

**Comment by psiborg112** [comment]
And yeah, that's what I suspected would happen. (Empty meters with no signal.) Just wanted to make sure it didn't crash. (Looked like it shouldn't but always worth checking.)

**Comment by psiborg112** [comment]
Unless... Have had an idea. Leave it with me.

**Comment by psiborg112** [comment]
Revised

**Comment by dyfer** [comment]
I think this works better.

I think this is a considerable UI change so I'd like others to chime in before merging this. However, this works for me. Here's a screenshot of JT once connected so that others can take a look without downloading:
Screen Shot 2022-11-09 at 10 04 18


(Also, I'm not sure what's wrong with Flatpak build failure, but I don't think it's related to this PR. @ntonnaett any ideas?)

**Review by dyfer — APPROVED** [review]
Works for me, but I'd like another approval before merging this.

**Comment by ntonnaett** [comment]
The flatpak build is failing because a security bug in git was fixed that breaks the flatpak-builder gha thingy. #797

**Comment by mattahorton** [comment]
This is great!

**Pull request merged**
