### PR TITLE
FreeBSD and other patches.

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by psiborg112** [comment]
Changes have already been merged to dev that should allow for JackTrip to run on FreeBSD. Is the dev branch not working as expected?

**Comment by yurivict** [comment]
This is a regression: ```1.5.0``` was building fine, but ```1.5.1``` is broken on FreeBSD.

**Comment by psiborg112** [comment]
Please try the dev branch. These changes have already been taken care of in #486.

**Comment by psiborg112** [comment]
And they will come out in version 1.5.2

**Comment by ntonnaett** [comment]
We should make a release.

**Comment by ntonnaett** [comment]
Should be working with 1.5.2 now.

**Pull request closed without merging**
