### PR TITLE
Fix stack use after scope

### PR DESCRIPTION
**Pull request by ntonnaett**
Fixs #355. No smart pointer needed.

### CODE REVIEW

**Comment by psiborg112** [comment]
This works, but I think smart pointers would be the safer way to handle it in the long run. At the very least, I think there needs to be a brief comment in the code about why the variable is created there because it would be easy to reintroduce the bug if the code is ever restructured, or if someone decides they can "optimise" it.

**Comment by ntonnaett** [comment]
Why do you think smart pointers are safer? I mean this goes out of scope when the whole application exits.

I will add a comment. The whole configuration has to be restructured at some point.

**Comment by psiborg112** [comment]
Safer in terms of this bug being less likely to reappear if someone restructures the code in main, although obviously a warning comment will do the job. It just seems like bad practice to have code so much further down the chain being dependent upon the command line parsing object remaining resident in memory long after its work is done.

**Comment by psiborg112** [comment]
(To clarify, I am still happy to approve this with just the warning comment.)

**Review by psiborg112 — APPROVED** [review]

**Pull request merged**
