### PR TITLE
Generate release data from yaml file for MkDocs and AppStream

### PR DESCRIPTION
**Pull request by ntonnaett**
Release data in the AppStream Metainfo file is a requirement for adding JackTrip to the Flathub repository. This PR moves the changelog data to a yaml file from where the changelog.md for Mkdocs and the metainfo file for flatpak are propagated.

### CODE REVIEW

**Comment by cchafe** [comment]
let me know if this is ready

**Comment by ntonnaett** [comment]
It's ready :)

**Comment by ntonnaett** [comment]
Let's complete the changelog in another PR.

**Review by cchafe — APPROVED** [review]

**Comment by cchafe** [comment]
ok -- I'll keep my  eye out for the changelog PR

**Pull request merged**
