### PR TITLE
Create separate arguments for input and output devices

### PR DESCRIPTION
**Pull request by maingig**
Fix for Issue #495. Use separate arguments for input and output devices.

### CODE REVIEW

**Comment by ntonnaett** [comment]
Thanks for your PR! Looks straight forward. Is this tested with device name including a comma?

Could you please rebase on dev!

**Comment by maingig** [comment]
I tested with these devices:
"Rogue Amoeba Software, Inc.: Loopback Audio 2"
"Rogue Amoeba Software, Inc.: Loopback Audio 1"

Looks like there was one format issue.  Do I need to fix that?

**Comment by ntonnaett** [comment]
I'm happy with this. The naming of the flags is nice for when we get tab completion one day. Let's see what others think. @dyfer @psiborg112 @cchafe

**Comment by psiborg112** [comment]
Looks good to me. Doesn't prevent people from doing things the current way if they're already in the habit of that (or have existing scripts they're using) while fixing the issue.

**Comment by ntonnaett** [comment]
> Looks good to me. Doesn't prevent people from doing things the current way if they're already in the habit of that (or have existing scripts they're using) while fixing the issue.

Do you have an idea for this? Counting the commas? May be something for another PR.

**Comment by psiborg112** [comment]
Oh no, I just meant that it doesn't stop the current option from working the way people are used to while adding the necessary options to fix the comma issue. I don't think there's a more elegant solution than that.

**Comment by ntonnaett** [comment]
Yeah, I agree. But the case for more than one comma for --audiodevice is broken. So we could warn if it's more than 1 and tell the user to use the new flags.

**Review by ntonnaett — APPROVED** [review]

**Comment by psiborg112** [comment]
Yes, a warning would probably be good in that circumstance - but definitely for a future PR.

**Comment by maingig** [comment]
Who is responsible for doing the merge? I'm not sure what your workflow is.

**Pull request merged**
