### PR TITLE
Vs dark mode

### PR DESCRIPTION
**Pull request by psiborg112**

### CODE REVIEW

**Comment by mattahorton** [comment]
> It seems this doesn't obey the global setting on linux. It would be great if this was supported.

Agreed. I'm betting there is a global check for all platforms in Qt and that is better than a button in the app, imo.

**Comment by psiborg112** [comment]
Then feel free to change how dark mode is being set.

**Comment by psiborg112** [comment]
(Although I do have to say that for development, being able to manually change it is extremely useful.)

**Comment by nwang92** [comment]
FWIW, the pattern I see everywhere is a "choose one of light, dark, or match system" which still preserves the development aspect. One example:
Screen Shot 2022-05-28 at 9 45 56 AM

**Comment by nwang92** [comment]
I'm seeing an empty screen on mac with these errors:
Screen Shot 2022-05-28 at 9 49 58 AM

**Comment by nwang92** [comment]
> I'm seeing an empty screen on mac with these errors: Screen Shot 2022-05-28 at 9 49 58 AM

I think I fixed it here? https://github.com/jacktrip/jacktrip/pull/602

**Comment by cchafe** [comment]
I've built the branch in qt and meson on fedora35 but both hang after launching GUI with ./jacktrip cmd
///////////////////////////////////////////////////////////////////////////////////////////////////////////////
qrc:/vs/vs.qml:85:5: Type Setup unavailable 
         Setup { 
         ^
qrc:/vs/Setup.qml:391:13: id is not unique 
                 id: backendCombo 
                 ^
SSL Library: OpenSSL 1.1.1n  FIPS 15 Mar 2022

**Review by nwang92 — APPROVED** [review]

**Comment by cchafe** [comment]
all good

**Pull request merged**
