### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by dyfer**
Clarify QJackTrip -> JackTrip

I thought it might be good to include that in the changelog? I'm open to suggestions in terms of wording etc.

### CODE REVIEW

**Comment by ntonnaett** [comment]
I think this should be shorter.

**Comment by dyfer** [comment]
> I think this should be shorter.

Sure. Suggestions?

**Comment by ntonnaett** [comment]
- include GUI from QJackTrip in JackTrip
- merge GUI…

**Comment by dyfer** [comment]
I would really like to indicate more clearly that QJackTrip is no more. But maybe we don't need to do it in the changelog, but instead on the release page

**Comment by cchafe** [comment]
--this seems to make sense--
(added) include GUI from QJackTrip in JackTrip
--and then--
(changed) QJackTrip and JackTrip are now identical

**Comment by dyfer** [comment]
How about this? (also, this is somewhat orthogonal to the release, we can tag rc.2 first as this will go on the github.io website anyway right after merging)

Also, if merging - please squash merge

**Review by cchafe — APPROVED** [review]

**Pull request merged**
