### PR TITLE
Catching a few cases where neither JACK not RtAudio are available

### PR DESCRIPTION
**Pull request by mattahorton**
This is a bit of ifdef hell, but I'd love a review. 

There's more we can do, but I think one of the things going on with some of our segfaults being reported is either JACK or RtAudio being set without the corresponding necessary definitions.

### CODE REVIEW

**Comment by dyfer** [comment]
Not a full review, but after building this on macOS without RtAudio there were no segfaults and the app started.

Not sure if that's relevant - the first run after building did _not_ start, emitting this:
<details>

``` sh
% builddir/jacktrip
qrc:/vs/vs.qml:126:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/vs/Setup.qml:632:17: Unable to assign [undefined] to QString
qrc:/vs/Setup.qml:741:17: Unable to assign [undefined] to QString
qrc:/vs/Settings.qml:311:17: Unable to assign [undefined] to QString
qrc:/vs/Settings.qml:394:17: Unable to assign [undefined] to QString
SSL Library: Secure Transport, macOS 12.6
Log file location: "/Users/marcin/Library/Application Support/jacktrip/JackTrip/log.txt"
^C # this is where I stopped it
```
</details>

Then I started Jack and the subsequent starts were fine. Not sure if that's relevant as I'm not able to reproduce this.

**Review by dyfer — COMMENTED** [review]
I am not very familiar with the implementation, but I was wondering if maybe it would be possible to add a function to `VsAudioInterface` like `getDefaultBackend` or something like that, where we'd do the `#ifdef` dance around `RT_AUDIO` and `NO_JACK`, which could replace at least ifdefs [here](https://github.com/jacktrip/jacktrip/pull/847/files#diff-d0c60d9b6f990a02918f8d909d0799c60c9883df2965760c8bb2f06d929130f2R77-R84) and [here](https://github.com/jacktrip/jacktrip/pull/847/files#diff-d0c60d9b6f990a02918f8d909d0799c60c9883df2965760c8bb2f06d929130f2R77-R84), what do you think?

**Comment by ntonnaett** [comment]
Just for my understanding. This is for the case that you chose a backend that was supported by a previous build and was saved, but isn't supported by the currently used build?! Do I miss other circumstances where this could happen?

IMHO we should get rid of macro hell and move to `if constexpr`. The benefit of `if constexpr` is that all branches of the code are checked by the compiler. It would require to also switch to C++17 for the qmake build. IIRC we actually already have C++17 code in jacktrip. 

The changes right now look good to me. Didn't test. If this fixes #845, we shouldn't wait too long with the merge. Afterwards we could work on a more beautiful overhaul maybe with `bool getDefaultBackend()` and `constexpr bool isBackendAvailable(API)`.

**Comment by ntonnaett** [comment]
I just build with NO_JACK and the audio backend selection includes JACK as an option. Is this expected behavior right now?

**Comment by mattahorton** [comment]
> I just build with NO_JACK and the audio backend selection includes JACK as an option. Is this expected behavior right now?

No

**Comment by mattahorton** [comment]
> I just build with NO_JACK and the audio backend selection includes JACK as an option. Is this expected behavior right now?

No

> Just for my understanding. This is for the case that you chose a backend that was supported by a previous build and was saved, but isn't supported by the currently used build?! Do I miss other circumstances where this could happen?
> 
> IMHO we should get rid of macro hell and move to `if constexpr`. The benefit of `if constexpr` is that all branches of the code are checked by the compiler. It would require to also switch to C++17 for the qmake build. IIRC we actually already have C++17 code in jacktrip.
> 
> The changes right now look good to me. Didn't test. If this fixes #845, we shouldn't wait too long with the merge. Afterwards we could work on a more beautiful overhaul maybe with `bool getDefaultBackend()` and `constexpr bool isBackendAvailable(API)`.

This

> Just for my understanding. This is for the case that you chose a backend that was supported by a previous build and was saved, but isn't supported by the currently used build?! Do I miss other circumstances where this could happen?
> 
> IMHO we should get rid of macro hell and move to `if constexpr`. The benefit of `if constexpr` is that all branches of the code are checked by the compiler. It would require to also switch to C++17 for the qmake build. IIRC we actually already have C++17 code in jacktrip.
> 
> The changes right now look good to me. Didn't test. If this fixes #845, we shouldn't wait too long with the merge. Afterwards we could work on a more beautiful overhaul maybe with `bool getDefaultBackend()` and `constexpr bool isBackendAvailable(API)`.

This is definitely the next thing I want to do.

**Comment by mattahorton** [comment]
> 

@dyfer your experience answers the question @ntonnaett asked. I think this only happens if you run a build now that was unsupported in the last build you ran. 

@cchafe was having this issue when building from source and that seems to match his experience too.

**Comment by ntonnaett** [comment]
> > I just build with NO_JACK and the audio backend selection includes JACK as an option. Is this expected behavior right now?
> 
> No

But at least it doesn't seem to be a regression.

**Review by ntonnaett — APPROVED** [review]

**Comment by mikedickey** [comment]
I think this is definitely better, but ideally it should handle a few more cases:

* `NO_JACK` defined and `RT_AUDIO` not defined => compile time error/failure
* calling `VsAudioInterface::setAudioInterfaceMode` at runtime with a value not supported by compile time definitions => error or ignore

**Comment by ntonnaett** [comment]
> 

The first point should be dealt with in the build system. I'll create a PR for meson.

**Pull request merged**
