### PR TITLE
Fix PROCESSENTRY warnings

### LINKED ISSUE #454: Missing initializer for PROCESSENTRY32 type
This looks funky.

```bash
 g++ -c -fno-keep-inline-dllexport -O2 -std=gnu++11 -pthread -ffunction-sections -fdata-sections -Wall -Wextra -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_OPENSOURCE -DWAIRTOHUB -D__RT_AUDIO__ -DUSE_WEAK_JACK -D__WIN_32__ -D_WIN32_WINNT=0x0600 -DWIN32_LEAN_AND_MEAN -D__WINDOWS_ASIO__ -D__WINDOWS_WASAPI__ -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../jacktrip -I. -Ifaust-src-lair/stk -I"C:/Program Files/JACK2/include" -I../externals/weakjack -Ifaust-src-lair -IC:/vcpkg/installed/x64-mingw-static/include/rtaudio -I../../qt-static/include -I../../qt-static/include/QtWidgets -I../../qt-static/include/QtGui -I../../qt-static/include/QtNetwork -I../../qt-static/include/QtCore -Irelease -I. -I../../qt-static/mkspecs/win32-g++  -o release/main.o ../src/main.cpp
../src/main.cpp: In function 'bool isRunFromCmd()':
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::cntUsage' [-Wmissing-field-initializers]
     PROCESSENTRY32 pe = {0};
                           ^
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::th32ProcessID' [-Wmissing-field-initializers]
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::th32DefaultHeapID' [-Wmissing-field-initializers]
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::th32ModuleID' [-Wmissing-field-initializers]
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::cntThreads' [-Wmissing-field-initializers]
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::th32ParentProcessID' [-Wmissing-field-initializers]
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::pcPriClassBase' [-Wmissing-field-initializers]
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::dwFlags' [-Wmissing-field-initializers]
../src/main.cpp:168:27: warning: missing initializer for member 'tagPROCESSENTRY32W::szExeFile' [-Wmissing-field-initializers]
```

### PR DESCRIPTION
**Pull request by psiborg112**
Fixes #454

### CODE REVIEW

**Comment by psiborg112** [comment]
Sorry, there are a few whitespace fixes in there as well. Only the first change needs to checking.

**Comment by ntonnaett** [comment]
Are the whitespace fixes made by clang-format?
Ist ZeroMemory used because the type is also a macro?
[Microsoft said you might want to use the safe variant.](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366920(v=vs.85)) Whatever that means…

**Comment by psiborg112** [comment]
Yes, whitespace fixes were detected by clang-format. ZeroMemory is used as a language agnostic standard part of the windows API. It'll use whatever underlying mechanism is determined to be the best one by the compiler. Since we're not dealing with secure data, if the compiler decides that it can optimize the macro away then it won't matter to us. (Which is what the SecureZeroMemory macro is designed to avoid.)

**Comment by psiborg112** [comment]
Since we're deep in windows API territory with this one it just seemed sensible to keep it consistent.

**Review by ntonnaett — APPROVED** [review]
Alright! Thanks!

**Pull request merged**
