### PR TITLE
Update installer scripts

### PR DESCRIPTION
**Pull request by psiborg112**
Add an option to specify the binary location in the MacOS packaging script to allow easier signing of downloaded github artifacts.

Allow upgrades with Windows installer.

Use a smart pointer for the AudioTester so that we don't need to keep the Settings object around.

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @psiborg112 
My personal preference would be to have separate commits for cpp changes and installer/script changes, but it's not a big deal.
I can confirm that with this PR one can install Windows version over the previous one.

**Review by dyfer — APPROVED** [review]
Thanks!

**Comment by dyfer** [comment]
@cchafe since this fixes an issue with Windows installer, maybe we should merge this before making rc.5?

**Comment by psiborg112** [comment]
@dyfer yeah, usually I'd split them out, but just didn't have time in this case.

**Pull request merged**
