### PR TITLE
Preview docs in Github Actions

### PR DESCRIPTION
**Pull request by dyfer**
I wanted to have an option of previewing documentation changes even if I don't have access to configured environment with mkdocs installed.

This PR adds a GHA job that runs _only on PRs_ and _only on docs changes_, creating a static version of the docs. They are then uploaded as GHA artifacts. This allows previewing the changes from a static rendering, without the need to run mkdocs locally.

This still requires to download the archive, uncompress it and open `*.html` file(s) in the browser, it does not create an online-viewable preview.

Not sure if others will find this useful... any feedback is welcomed!

### CODE REVIEW

**Review by ntonnaett — APPROVED** [review]
Nice idea! Looks fine. I assume this only works if it is already merged.

**Comment by dyfer** [comment]
Thanks! It works for PRs that make actual changes to the docs, so not _this_ PR :). Here's an example how it works when made it run of every push: https://github.com/jacktrip/jacktrip/actions/runs/4069416120 (I later fixed the reason for node 12 action warning)

**Comment by ntonnaett** [comment]
> Thanks! It works for PRs that make actual changes to the docs, so not _this_ PR :). Here's an example how it works when I made it run on every push: https://github.com/jacktrip/jacktrip/actions/runs/4069416120 (I later fixed the reason for node 12 action warning)

Of course. Might be really helpful for some people.

**Comment by dyfer** [comment]
@ntonnaett OK to merge? (I'm double checking since I removed the repository check)

**Comment by ntonnaett** [comment]
> @ntonnaett OK to merge? (I'm double checking since I removed the repository check)

Looks good. One additional idea to make it faster to use would be to put everything in a subdirectory in the zip file. But I remember that these things are difficult with GHA.

**Comment by dyfer** [comment]
> One additional idea to make it faster to use would be to put everything in a subdirectory in the zip file.

Like [this](https://github.com/dyfer/jacktrip/actions/runs/4069679099)?

**Comment by ntonnaett** [comment]
> > One additional idea to make it faster to use would be to put everything in a subdirectory in the zip file.
> 
> Like [this](https://github.com/dyfer/jacktrip/actions/runs/4069679099)?

Yes. But… So double subdirectories in artefacts is just something that happens with releases?!

**Comment by dyfer** [comment]
> So double subdirectories in artefacts is just something that happens with releases?!

IIRC... Not exactly. Artifact upload on GHA ("Checks") page _always_ compresses files from the provided path into a zip file, even if it already is a single archive. I'm telling it to upload a directory, so it makes an archive from that.
However, this is not what happens for releases, where files are upload as they are listed, without being additionally packaged into an archive, so if you define a single zip then this is what is being uploaded.

We could presumably fix the double-zip issue by not creating the archive for artifact upload (we'd still need to create it for releases though).

**Comment by dyfer** [comment]
I've added adding files into a subdirectory called the same as the archive (`JackTrip-docs-<sha>`). Looks good?

**Comment by ntonnaett** [comment]
> I've added the commit that moves files into a subdirectory named the same as the archive (`JackTrip-docs-<sha>`). Looks good?

Perfect

**Pull request merged**
