### PR TITLE
CMake build customisations

### PR DESCRIPTION
**Pull request by psiborg112**
These changes only impact my CMake builds. Incorporating them will remove the need for me to maintain my own custom fork, which means I can spend more of my limited dev time on more useful and important things.

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @psiborg112 
I believe this PR also includes commits from #748 and #749 (?) If that's the case, should they stay here or be removed from this PR?

Also, would you be okay if I added cmake build to our CI or do you still consider it to be "internal use only"? Ideally it would be great to have at least rudimentary instructions for building with CMake, either on the [docs page](https://jacktrip.github.io/jacktrip) or even included in a comment here...

**Comment by psiborg112** [comment]
Given they've just been merged it probably doesn't matter too much. And yeah, happy for you to do that although it might be of limited use. I think it should work on most linux distros, and I'm about to make some changes that should allow it to be a bit more flexible on windows. It would be interesting to see if it works for others on Mac. (I use a custom patched macports install of Qt to allow me to make universal binaries. Might need to make some changes for homebrew.)

**Comment by ntonnaett** [comment]
Would you mind rebasing and fixing the conflicts? I think it's better to merge this ASAP if nothing is missing in your point of view.

**Review by ntonnaett — APPROVED** [review]

**Comment by dyfer** [comment]
I wanted to do a full review, testing cmake etc... but if we want to merge it first and then look at it more closely that's okay too, as nobody else is using cmake. I was just thinking I'd test it out and make rudimentary docs along the way, just haven't gotten around to it yet.

**Comment by ntonnaett** [comment]
No pressure. I just thought that it might be good for avoiding more merge conflicts and stop Aaron patching this on all his other branches. Horrifying that he did this all this time. Aaaand we should have more PRs. Nobody celebrated our 500th merged PR. I'm quite disappointed.

**Comment by dyfer** [comment]
> Nobody celebrated our 500th merged PR. I'm quite disappointed.

😀

**Comment by psiborg112** [comment]
Just to check though, the one thing in this that doesn't just affect me is the change to the install directory in windows - placing JackTrip in the 64 bit Program Files directory. Is that ok with everyone? (Otherwise I can move it out of this PR.)

**Comment by ntonnaett** [comment]
> Just to check though, the one thing in this that doesn't just affect me is the change to the install directory in windows - placing JackTrip in the 64 bit Program Files directory. Is that ok with everyone? (Otherwise I can move it out of this PR.)

Could this impact upgrades? Haven't we changed that in qmake yet?

**Comment by psiborg112** [comment]
It's changed in the windows installer script. It shouldn't affect upgrades, beyond possibly leaving an old version of the file lying around in the former directory. (But this won't be pointed to any more in the start menu, so the user wouldn't see an impact.)

**Comment by psiborg112** [comment]
(It fixes something that was noted tangentially to #725 - that we're incorrectly installing in the 32 bit program files folder.)

**Comment by ntonnaett** [comment]
Sounds fine to me.

**Pull request merged**
