### PR TITLE
GHA: Update Qt to version 5.15.8

### PR DESCRIPTION
**Pull request by ntonnaett**
Not sure if I have to do anything about *Windows-x64-qmake-gcc-shared* and *Windows-x64-meson-msvc-shared*.

### CODE REVIEW

**Comment by ntonnaett** [comment]
There's only 5.15.2 for shared Windows… https://www.qt.io/offline-installers

**Comment by dyfer** [comment]
> There's only 5.15.2 for shared Windows…

Yes, Qt 5 above 5.15.2 is only available as source code, so the official binaries won't be available for them.

**Comment by ntonnaett** [comment]
I think that's okay for now. Maybe we could add shared libraries to our qt build. That shouldn't be any real overhead.

**Comment by ntonnaett** [comment]
Thanks for testing!

**Pull request merged**
