### PR TITLE
Enforce Same ASIO Device on Windows

### PR DESCRIPTION
**Pull request by dhing1024**
Doesn't require any changes to UI code. But we may want to update the help article at https://help.jacktrip.org/hc/en-us/articles/4409919243155

### CODE REVIEW

**Comment by mikedickey** [comment]
I'm still getting the same scary popup messages when using a build from github actions

**Comment by dhing1024** [comment]
Still a WIP

**Comment by dhing1024** [comment]
I think this should be good now, but not totally sure. Will need someone other than me to test ASIO.

**Comment by mikedickey** [comment]
If I change either the input or output device to an ASIO device, the backend seems to change the other device to match the same one, but it doesn't update the selection list shown in the user interface for it. The selection list still displays the old device I had selected previously, even though it's no longer being used.

**Review by mikedickey — APPROVED** [review]

**Pull request merged**
