### PR TITLE
Optimize circular buffer for feedback detection

### PR DESCRIPTION
**Pull request by mikedickey**
Push and pull buffers of samples rather than one at a time

Add buffer size to ProcessPlugin::init and other related code cleanup

### CODE REVIEW

**Comment by mikedickey** [comment]
I've observed that the new feedback detection feature still roughly doubles jacktrip's CPU usage on my M2 MacBook. I tracked this down specifically to the Faust code, or this line:

```static_cast<fftdsp*>(mFftP)->compute(samples, &data, mAnalysisBuffers);```

Not sure if there is way to optimize that any further?

**Comment by cchafe** [comment]
In fftdsp.dsp he FFT size is 128
the documentation says it will perform a sliding FFT over a real input signa
does that mean full hops?
(if sliding means each sample, then that's problematic)

**Comment by mikedickey** [comment]
> In fftdsp.dsp he FFT size is 128
> the documentation says it will perform a sliding FFT
> does that mean full hops?
> (if sliding means each sample, then that's problematic)

Hi @cchafe, I believe @demarcod1 is out today, but I will forward this to him via Slack

**Review by nwang92 — APPROVED** [review]

**Comment by mikedickey** [comment]
I'm going to merge to roll a beta2 today with the latest. Feedback detection definitely needs more work, but this will help get it more testing. Going to leave it disabled by default for now.

**Pull request merged**
