### PR TITLE
GHA: Add JTL signing scripts

### PR DESCRIPTION
**Pull request by mattahorton**
### ~~Not quite ready to merge. Will add a note when it is.~~ We're good to go.

This is the script from the JackTrip Labs fork that we use to sign app bundles and installers. Bringing it over so we can keep `main` and `dev` in sync with this repo. 

The GHA script should not even run in this repo given it does not have the appropriate secret, but I can't test that without making a PR first.

### CODE REVIEW

**Comment by mattahorton** [comment]
When these checks finished, this should be good to merge.

**Review by mikedickey — APPROVED** [review]

**Comment by dyfer** [comment]
just a note on "not ready to merge" - there's an option to "draft a PR". Draft PRs can't be merged - that's a great option to make sure it's not merged until it's ready.

**Comment by dyfer** [comment]
Just a note on "not ready to merge" - there's an option to "draft a PR". Draft PRs can't be merged - that's a great option to make sure it's not merged until it's ready.

**Comment by dyfer** [comment]
Just a note on "not ready to merge" - there's an option to "draft a PR". Draft PRs can't be merged - that's a great option to make sure it's not merged until it's ready.

**Comment by dyfer** [comment]
just a note on "not ready to merge" - there's an option to "draft a PR". Draft PRs can't be merged - that's a great option to make sure it's not merged until it's ready.

**Pull request merged**
