### PR TITLE
Minor Wording Adjustments on Connected Screen

### PR DESCRIPTION
**Pull request by dhing1024**
Any chance we could squeeze this in to 1.7.0 or is it too late for that? (I don't mind if we push it to the next one)

https://user-images.githubusercontent.com/26987971/213780577-a8513bb9-4f73-4cf6-bc6d-d5e15deb4f44.mov

### CODE REVIEW

**Comment by mattahorton** [comment]
Dominick i wish you had dm'd me

**Comment by dhing1024** [comment]
Sorry about that. Got DM'd by Mike asking to do some adjustments with text and buttons to better sync it with the Web UI. We can defer on this since it's not in the 1.6.9 release plan and I don't think this is the most important thing to have.

**Comment by mattahorton** [comment]
Gotcha. No worries. It'll get in the next one.

**Review by nwang92 — APPROVED** [review]

**Comment by mattahorton** [comment]
Do not merge this until we release

**Review by mikedickey — APPROVED** [review]

**Pull request merged**
