### PR TITLE
Release 1.8.1

### PR DESCRIPTION
**Pull request by mattahorton**
Lots of good fixes and code cleanup in this one

### CODE REVIEW

**Comment by mattahorton** [comment]
This merge is being held up by an [issue in vcpkg](https://github.com/microsoft/vcpkg/pull/30546)

**Comment by mattahorton** [comment]
Created #988 to address this

**Comment by mattahorton** [comment]
I am not sure what’s going on. That switch worked in #988, but when merged to dev doesn’t work on the checks here in #987.

I looked into it, and it seems that the #988 builds are pulling from a 3/29 vcpkg cache and for some reason, #987 is pulling from a 3/26 cache. So maybe the chocolatey switch did nothing?

Does anyone know more about Actions than me that could explain it?

**Comment by mattahorton** [comment]
Looks like the `pull_request` trigger is the one that is broken. The `push` trigger is not. 

How should we proceed?

**Comment by psiborg112** [comment]
From my understanding of briefly reading around, it doesn't seem like it's possible to get vcpkg to use an existing install of msys2. (Someone had proposed creating an environment variable to allow it, but don't know that it made it into any releases.)

**Comment by dyfer** [comment]
> I looked into it, and it seems that the #988 builds are pulling from a 3/29 vcpkg cache and for some reason, #987 is pulling from a 3/26 cache.

Cache created either from the current branch, or the default branch can be accessed by the cache action. But sometimes I'm confused myself what has access to what (e.g. pull request vs push).

I haven't looked into the underlying issue (vcpkg/msys).

**Comment by mikedickey** [comment]
looks like microsoft change for vcpkg has merged. should we roll back the choco change and try again?

**Comment by mattahorton** [comment]
> looks like microsoft change for vcpkg has merged. should we roll back the choco change and try again?

on it

**Comment by mattahorton** [comment]
Well. 

I'm no longer convinced that even a new vcpkg release would fix the issue. I'm working on updating the script to reinstall vcpkg from a commit hash.

**Pull request merged**
