### PR TITLE
Rtaudio subproject fixes

### PR DESCRIPTION
**Pull request by ntonnaett**
Sorry @dyfer! There were some flags missing. I forgot to pass the defines to the compiler. But no linking errors occured.

### CODE REVIEW

**Comment by dyfer** [comment]
Have you tried running this build on Windows? DependenciesGui shows some missing dependencies (inside `WS2_32.dll` and `DSOUND.dll`) and I can't run it because of that, despite Qt actually being found.

**Comment by ntonnaett** [comment]
As I said. I don't have Windows. Both libraries are not part of jacktrip. So I don't understand what DependenciesGui is telling you. Could you post the output? Did you build it yourself?

**Comment by ntonnaett** [comment]
Maybe you don't have DirectX installed?!

**Comment by dyfer** [comment]
> As I said. I don't have Windows. Both libraries are not part of jacktrip. So I don't understand what DependenciesGui is telling you. 

I really can't be much help, aside from reporting what does and does not work, sorry.

> Could you post the output? 

I'll try later.

> Did you build it yourself?

No, I used the build from GHA.

> Maybe you don't have DirectX installed?!

Is that even needed in Windows 10? Also, dev JT build (with RtAudio) works fine.

BTW it doesn't seem like you're building with DirectSound, but one of the missing dependencies suggests that maybe you do? Would be worth double checking parsing options etc.

It does seem like you have all linker flags in place. However, I had a problem with linking on windows in qmake - these windows flags needed to be [specified](https://github.com/jacktrip/jacktrip/blob/rtaudio_subproject_fixes/jacktrip.pro#L143) _after_ `-lrtaudio`. This is with MinGW so maybe not relevant, but I thought I'd point it out. And also - I had to link JackTrip with these libraries, rtaudio itself was not enough.

I wonder if you could run JT in wine to test these things... though probably that poses its own set of problems.

**Comment by ntonnaett** [comment]
I tried with wine and it's only complaining about missing Qt5 in the beginning. Copying from mingw doesn't work because jacktrip is compiled with msvc. Dev works fine because it has no backends built.

Right now I try to get the cmake flags for wingetopt right. Maybe it's easier to include those files in jacktrip at some point in the future.

**Comment by dyfer** [comment]
> I tried with wine and it's only complaining about missing Qt5 in the beginning. Copying from mingw doesn't work because jacktrip is compiled with msvc. Dev works fine because it has no backends built.

Ah! Maybe it's a mistake on my end? The binary from this build picked up Qt in the MinGW folder. Trying now

**Comment by ntonnaett** [comment]
I am cleaning up right now too. Maybe you want to wait. I found some things with wingetopt that weren't right.

**Comment by ntonnaett** [comment]
Ready!

**Comment by dyfer** [comment]
I'm so SORRY Nils I have sent you on a wild goose chase.

After Installing Qt 5.15 for msvc and adding that to PATH I can start this build of JT. Interestingly, DependenciesGui still complains about WS2_32 and DSOUND dlls, but the applications starts properly.

Just to re-iterate: I can start both the build I've downloaded previously, as well as the current build.

Sorry again.

**Review by dyfer — APPROVED** [review]
Thanks!

are you leaving `compile -v` in for now?

**Comment by ntonnaett** [comment]
The current build has less warnings. So it was beneficial nevertheless.

I remove the -v. I don't think that we need this level of information for static qt.

**Pull request merged**
