### PR TITLE
GitHub Actions: remove link time optimization for Linux/macOS

### LINKED ISSUE #391: GHA: ODR violation in Linux build
See: https://github.com/jacktrip/jacktrip/runs/3438184706?check_suite_focus=true#step:14:104

### LINKED ISSUE #393: GHA: macOS linker warnings
See: https://github.com/jacktrip/jacktrip/runs/3438184759?check_suite_focus=true#step:14:118

### PR DESCRIPTION
**Pull request by dyfer**
~~Added: upgrade Qt to 5.15 on macOS, see https://github.com/jacktrip/jacktrip/issues/393#issuecomment-917340168~~

~~possibly fixes #393, maybe #391?~~
AFAICT this fixes #391

### CODE REVIEW

**Comment by ntonnaett** [comment]
Argh, Flatpak, those hashes :/ But Linux build seems to be fixed.

**Comment by dyfer** [comment]
While upgrading Qt on macOS might be OK in general (it seems our build did not run on macOS 10.12 anyway, maybe because of homebrew libraries or some other settings), it did not remove linker warnings. I'm not sure if that change should be a part of this PR or not. More info in #393

**Comment by ntonnaett** [comment]
Should we merge this as is?

**Comment by dyfer** [comment]
Let me remove Qt change, as it doesn't fix anything ATM

**Review by ntonnaett — APPROVED** [review]

**Pull request merged**
