### PR TITLE
Updating styles of meter bars to be responsive

### PR DESCRIPTION
**Pull request by nwang92**
Adds a faint glow when bars are lit up, and also makes the bars scale responsively + fill in any gaps when the width changes.

https://github.com/jacktrip/jacktrip/assets/6201822/8d255365-b959-4c0a-bf31-1466b016c536

### CODE REVIEW

**Comment by mikedickey** [comment]
I'm getting qml errors and a blank white window when I try to run it

```
➜  jacktrip git:(feature/responsive-meter-bars) ✗ ./builddir/jacktrip
qrc:/vs/vs.qml:102:5: Type Setup unavailable
         Setup {
         ^
qrc:/vs/Setup.qml:553:9: Type AudioSettings unavailable
             AudioSettings {
             ^
qrc:/vs/AudioSettings.qml:225:13: Type Meter unavailable
                 Meter {
                 ^
qrc:/vs/Meter.qml:21:9: Type MeterBars unavailable
             MeterBars {
             ^
qrc:/vs/MeterBars.qml:3:1: module "QtQuick.Layouts" plugin "qquicklayoutsplugin" not found
     import QtQuick.Layouts 1.15
     ^
```

**Comment by mikedickey** [comment]
> I'm getting qml errors and a blank white window when I try to run it

Nevermind, wiping out builddir and doing a clean build seemed to resolve it. Just qmake bugs...

**Review by mikedickey — CHANGES_REQUESTED** [review]
This more than doubles cpu usage on my Mac.

**Comment by nwang92** [comment]
> This more than doubles cpu usage on my Mac.

Hmm I guess rendering the extra glow effect is pretty expensive. I removed that but kept the responsive layout and that seems to fix it

**Review by mikedickey — APPROVED** [review]
Removing glow seems to fix the cpu regression

**Pull request merged**
