### PR TITLE
Switch github actions to using new qt assets built using qtbuild

### PR DESCRIPTION
**Pull request by mikedickey**
This updates the release packages for both Windows and OSX to using Qt 6.2.4 dynamic and removes all the logic for building qt from source from the GitHub Actions.

It still is split between using qtbuild and the GitHub Actions cache for statics, while downloading dynamics. I'll work on removing all the remaining static build stuff in favor of using external packages for those as well as another PR once I have everything finished with the new jacktrip-qt repo.

~It also still needs the virtual studio QML updates for qt6 from @nwang92's `feature/qt6-nwang` branch. But I think it may be easier to merge this first and then create a new PR for the QML updates. This one is already pretty big, and his batch of changes is at least as large.~

This now incorporates fixes for porting VS QML to qt6 and some other things I pulled from @ntonnaett 's [original PR](https://github.com/jacktrip/jacktrip/pull/557)

### CODE REVIEW

**Comment by mikedickey** [comment]
I believe this is all working now. I'll work on moving out all the remaining logic for building qt and switch everything over to external packages as another PR.

**Comment by nwang92** [comment]
The build errors with:
```
../src/main.cpp:40:10: fatal error: QQuickStyle: No such file or directory
   40 | #include <QQuickStyle>
```

I guess this library is only available on Qt6. I think we can fix it by changing modifying these lines:
```
#ifndef NO_GUI
#include <QApplication>
#if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
#include <QQuickStyle>
#endif  // QT_VERSION
```

**Comment by ntonnaett** [comment]
> The build errors with:
> 
> ```
> ../src/main.cpp:40:10: fatal error: QQuickStyle: No such file or directory
>    40 | #include <QQuickStyle>
> ```
> 
> I guess this library is only available on Qt6. I think we can fix it by changing modifying these lines in main.cpp:
> 
> ```
> #ifndef NO_GUI
> #include <QApplication>
> #if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
> #include <QQuickStyle>
> #endif  // QT_VERSION
> ```

According to [this](https://doc.qt.io/qt-5/qquickstyle.html) it should be available since version 5.7.

**Comment by mikedickey** [comment]
Seems like I broke SVG support in the OSX application package and installer.. 

Screenshot 2023-07-12 at 1 39 25 PM

```
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/sentiment_very_dissatisfied.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/speed.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/help.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/help.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/help.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/mic.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/headphones.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/mic.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/refresh.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/mic.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/help.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/headphones.svg: Unsupported image format
qrc:/qt-project.org/imports/QtQuick/Controls/Basic/Button.qml: QML IconImage: Error decoding: qrc:/vs/help.svg: Unsupported image format```

**Review by nwang92 — APPROVED** [review]

**Pull request merged**
