### PR TITLE
VS: Handle macOS mic permissions gracefully 

### PR DESCRIPTION
**Pull request by mattahorton**
Handles "microphone" permissions on macOS

"Don't Allow"
https://user-images.githubusercontent.com/5567285/201185419-40daca91-f813-4549-a789-8d6a851d6814.mp4

"OK"
https://user-images.githubusercontent.com/5567285/201185426-2bd2dded-a2d9-4a58-8586-91f3af9dd386.mp4

("Hyper" is my terminal app. It will say "JackTrip".)

### CODE REVIEW

**Comment by dhing1024** [comment]
I'm not really a huge fan of this info message:

> This app requires microphone access to allow the jack server to capture audio.

But otherwise as far as I can tell this seems to works on my M1 MacBook.

**Comment by mattahorton** [comment]
> I'm not really a huge fan of this info message:
> 
> > This app requires microphone access to allow the jack server to capture audio.
> 
> But otherwise as far as I can tell this seems to works on my M1 MacBook.

Yeah I'm not either. I did not change that from how it is now.

**Comment by mattahorton** [comment]
Just tested and currently getting a white screen on Windows

**Comment by mattahorton** [comment]
This should be ready to go.

**Comment by mattahorton** [comment]
There are some Linux issues here for Ubuntu users on old distros (testing on 20.04) but it seems to be because of the volume meter stuff. I will probably do a separate bug fix pr.

**Review by nwang92 — APPROVED** [review]

**Comment by dyfer** [comment]
I don't think this can be merged when there are conflicts...

**Comment by mattahorton** [comment]
> I don't think this can be merged when there are conflicts...

Yeah those came in from another PR. I'll fix them now.

**Comment by mattahorton** [comment]
@dhing1024 the only conflicts between my branch and #772 was the signal/slot connections in `slotAuthSucceeded`

```
connect(m_vsAudioInterface.data(), &VsAudioInterface::devicesErrorMsgChanged, this,
            &VirtualStudio::updatedDevicesErrorMsg);
connect(m_vsAudioInterface.data(), &VsAudioInterface::devicesWarningMsgChanged, this,
            &VirtualStudio::updatedDevicesWarningMsg);
```

I had created a `startAudio` method that does what it says and included all the vsAudioInterface connections in there.

I moved these lines into that method.

**Comment by dhing1024** [comment]
Just did some quick tests for both Mac and Windows and I think this is good.

**Review by dhing1024 — APPROVED** [review]

**Pull request merged**
