### PR TITLE
Fixing connected view errors

### PR DESCRIPTION
**Pull request by nwang92**
This should fix the remaining QML errors in https://github.com/jacktrip/jacktrip/issues/1036. My editor has a whitespace remover which touched a lot of other QML files but the relevant change is in `Connected.qml`

### CODE REVIEW

**Comment by ntonnaett** [comment]
I still have error messages, but I'm wondering if these are all related to a bug in the qt version that's used in the Flathub runtime/platform. It seems to be a syntax error in the following block in /usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:
```
Private.MobileCursor {
        target: controlRoot.contentItem
        selectionStartHandle: true
        readonly property rect rect: target.positionToRectangle(target.selectionStart)
        x: rect.x + 5
        y: rect.y + 6
    }
```

My interpretation: positionToRectangle is not a C++ function. But it needs an argument. How would you do this with qml? 

Current error messages for Flatpak (JACK only):
```
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Property 'positionToRectangle' of object QQuickText(0x556c132afea0) is not a function
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Property 'positionToRectangle' of object QQuickText(0x556c13277c10) is not a function
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Property 'positionToRectangle' of object QQuickText(0x556c1322efd0) is not a function
SSL Library:  "OpenSSL 3.0.8 7 Feb 2023"
Log file location: "/home/nils/.var/app/org.jacktrip.JackTrip/data/jacktrip/JackTrip/log.txt"
qrc:/vs/Connected.qml:343:33: Unable to assign [undefined] to QString
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
qrc:/vs/Connected.qml:533:33: Unable to assign [undefined] to QString
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
qrc:/vs/Connected.qml:533:33: Unable to assign [undefined] to QString
qrc:/vs/Connected.qml:343:33: Unable to assign [undefined] to QString
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
qrc:/vs/Connected.qml:533:33: Unable to assign [undefined] to QString
qrc:/vs/Connected.qml:343:33: Unable to assign [undefined] to QString
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
qrc:/vs/Connected.qml:533:33: Unable to assign [undefined] to QString
qrc:/vs/Connected.qml:343:33: Unable to assign [undefined] to QString
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
file:///usr/lib/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:117: TypeError: Type error
```

**Comment by ntonnaett** [comment]
It is related to the Flathub runtime. No errors or graphical glitches with the qmake build on Fedora 38.

**Comment by nwang92** [comment]
Thanks for checking! Let me see what's going on with the following and tack some fixes onto this PR:
```
qrc:/vs/Connected.qml:533:33: Unable to assign [undefined] to QString
qrc:/vs/Connected.qml:343:33: Unable to assign [undefined] to QString
```

**Review by ntonnaett — APPROVED** [review]
LGTM who doesn't really know QML.

**Review by dhing1024 — APPROVED** [review]

**Comment by ntonnaett** [comment]
I could reproduce all those TypeErrors that come from upstream Qt on bare-metal Fedora by installing the qqc2-desktop-style package. We might be able to fix it by [setting the style](https://doc.qt.io/qt-6/qtquickcontrols-styles.html).

**Comment by ntonnaett** [comment]
I opened #1058 for the flatpak style fix.

**Pull request merged**
