### PR TITLE
Merge main to dev

### PR DESCRIPTION
**Pull request by dyfer**
This is my attempt to merge main to dev... not sure if this is correct?

### CODE REVIEW

**Comment by ntonnaett** [comment]
What's the advantage to the PR that has just the hotfix commit?

**Comment by dyfer** [comment]
what I did was:
- update `dev` from `upstream` (this repo)
- create new branch `mp/merge-main-to-dev` based on `dev`
- merge `main` into that branch
- create PR from that branch
I was expecting merge conflicts that's why I created a separate branch for the merge, it if there are none, we should be able to just merge `main` into `dev` directly... maybe?

**Comment by ntonnaett** [comment]
Do we need this if nothing changes?

**Comment by mikedickey** [comment]
Just tried same and got the same result: no changes as a result of the merge. Agree that it may therefore not be necessary? We could just wait on this until after there are changes in main that we want to also migrate to dev.

**Comment by ntonnaett** [comment]
For example merge #237 to main and then main to dev?

**Comment by dyfer** [comment]
Yeah, I think #237 would be a good candidate to test this workflow - a small change, but one that we want to have in both branches (I presume sooner than later).

**Comment by mikedickey** [comment]
If you do another merge from main into this PR branch, it should pick up the changes in the PR

**Comment by dyfer** [comment]
Hm, maybe I messed this up. I removed previous "merge" commit (using rebase) and merged from main again. But it doesn't look right now does it?

**Comment by dyfer** [comment]
Okay, I redid it. I reset this branch to dev, merged main, and force pushed. I think it's correct. What do you think @mikedickey ?

**Comment by mikedickey** [comment]
@dyfer Looks right to me!

**Review by mikedickey — APPROVED** [review]

**Pull request merged**
