### PR TITLE
VS: New First Launch screen

### PR DESCRIPTION
**Pull request by mattahorton**
This is the first launch screen we talked about in the last dev meeting.

Screen Shot 2022-05-12 at 1 22 59 PM

### CODE REVIEW

**Comment by ntonnaett** [comment]
What I would like is an association of those buttons to Virtual Studio Mode and Classic Mode. Did we decide for "Classic"?

**Comment by mattahorton** [comment]
> What I would like is an association of those buttons to Virtual Studio Mode and Classic Mode. Did we decide for "Classic"?

We did, but I thought it after that discussion that this screen would be a yes or no question and that buttons in the interfaces would reference Classic mode and Virtual Studio mode.

**Comment by ntonnaett** [comment]
I'm totally for the yes or no buttons. I thought of something like smaller labels below Yes and No.

**Comment by mattahorton** [comment]
> I'm totally for the yes or no buttons. I thought of something like smaller labels below Yes and No. Or just emphasize Virtual Studio and Classic in the list below.

The context of the discussion was that we wanted to avoid branding either experience on this page, I thought. We knew we couldn't really get away from it when someone needs to switch. Otherwise we would have gone with one of the ones that had those names more prominent in the UI.

**Comment by mikedickey** [comment]
Looks like "Virtual Studios" is already in the bullet list for "Yes". How about we just change the text on the "No" side to "The Classic JackTrip experience"

**Review by mikedickey — APPROVED** [review]

**Pull request merged**
