### PR TITLE
Fix for OSX installer failures

### LINKED ISSUE #430: 1.4.0 osx installer fails when missing /usr/local/bin
Running the OS X installer on Big Sur (11.6) Intel. After it reaches the last step and seems to be running some package verification step it displays the message: "The Installation Failed" (see screenshot attached).

Despite the error message, the installer actually seems to have worked correctly. JackTrip is installed in the Applications folder, and appears to work just fine.

jacktrip_installation_failed
..

### PR DESCRIPTION
**Pull request by mikedickey**
Fixes #430

create /usr/local/bin directory if it doesn't already exist

### CODE REVIEW

**Comment by ntonnaett** [comment]
Could you bump the version to 1.4.1?

**Comment by ntonnaett** [comment]
In #430 you used sudo. Isn't that needed for the installer?

**Comment by mikedickey** [comment]
> In #430 you used sudo. Isn't that needed for the installer?

I'm not sure, but was assuming that since the script was executing successfully without sudo before (assuming the directory existed), the installer must already be running it with elevated permissions.

**Review by dyfer — APPROVED** [review]
I tested this on a Big Sur installation with non-existing `/usr/local/bin` and can confirm that the destination folder was created correctly. The installer itself is elevating privileges with a GUI prompt before performing the installation.

**Comment by dyfer** [comment]
The only outstanding question is whether we merge this into `main` or create a separate release branch. I'm happy to go either way, but I think that merging to main might be easier (if we are not planning a long "patch release" cycle). Does anyone have objections agains merging this into `main` directly? (@cchafe @ntonnaett)

**Comment by ntonnaett** [comment]
I would prefer merging this directly.

**Review by cchafe — APPROVED** [review]

**Pull request merged**
