### PR TITLE
Let's release 1.6.2

### PR DESCRIPTION
**Pull request by mattahorton**
~Pending the version bump and changelog updates in #691, let's release 1.6.2.~

Let's release 1.6.2.

Would love to hear thoughts from everyone. As a reminder, here's a copy/paste of the changelog.

**Updates in 1.6.2**
  - (updated) Static Qt version for Linux builds
  - (upated) cleaner, easier to read VS settings
  - (updated) icons for 'Manage' and 'Settings' in VS mode
  - (added) human-readable locations in VS mode
  - (added) warning that cmake is not officially supported
  - (added) VS mode is treated as a device by VS web
  - (added) Network statistics in Virtual Studio mode
  - (added) URL scheme support to join a Studio from the VS web join button
  - (added) banner images on Studios in VS mode
  - (added) VS mode sets remote client name to app ID
  - (fixed) WebSocket connection behavior in Virtual Studio (VS) mode
  - (fixed) dblsqd errors in Linux builds
  - (fixed) Windows datagramAvailable error
  - (fixed) High Sierra compatibility in static builds
  - (fixed) Doesn't crash if RtAudio sample rate isn't supported
  - (fixed) Fractional UI scaling on Windows

### CODE REVIEW

**Comment by ntonnaett** [comment]
Following warnings are a result of #ifdef hell. Would be great to silence those with [[maybe_unused]] and clean it up later.

```
../src/gui/vsDevice.cpp: In Elementfunktion »JackTrip* VsDevice::initJackTrip(bool, std::string, std::string, int, VsServerInfo*)«:
../src/gui/vsDevice.cpp:257:39: Warnung: unverwendeter Parameter »useRtAudio« [-Wunused-parameter]
  257 | JackTrip* VsDevice::initJackTrip(bool useRtAudio, std::string input, std::string output,
      |                                  ~~~~~^~~~~~~~~~
../src/gui/vsDevice.cpp:257:63: Warnung: unverwendeter Parameter »input« [-Wunused-parameter]
  257 | JackTrip* VsDevice::initJackTrip(bool useRtAudio, std::string input, std::string output,
      |                                                   ~~~~~~~~~~~~^~~~~
../src/gui/vsDevice.cpp:257:82: Warnung: unverwendeter Parameter »output« [-Wunused-parameter]
  257 | JackTrip* VsDevice::initJackTrip(bool useRtAudio, std::string input, std::string output,
      |                                                                      ~~~~~~~~~~~~^~~~~~
../src/gui/vsDevice.cpp:258:38: Warnung: unverwendeter Parameter »bufferSize« [-Wunused-parameter]
  258 |                                  int bufferSize, VsServerInfo* studioInfo)
      |                                  ~~~~^~~~~~~~~~
```

Rest seems fine to me. Are the pictures of cities getting redownloaded when scrolling them out of and back in focus?

**Comment by mattahorton** [comment]
> Following warnings are a result of #ifdef hell. Would be great to silence those with [[maybe_unused]] and clean it up later.
> ...
> Rest seems fine to me. Are the pictures of cities getting redownloaded when scrolling them out of and back in focus?

we can clean that up.

great question. @nwang92 do you know if those are reloaded when scrolled into view?

**Comment by nwang92** [comment]
Mostly likely they're being re-downloaded

**Comment by mattahorton** [comment]
I looked it up. If it's a Qml image, they're cached by default.

**Comment by dyfer** [comment]
If that's okay, I'd propose merging #693 before the release.

**Comment by mattahorton** [comment]
@ntonnaett I've addressed those warnings with `[[maybe_unused]]` in #694

**Review by ntonnaett — APPROVED** [review]

**Pull request merged**
